# Generated by Django 4.2.4 on 2023-08-23 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_count', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='train_user', to=settings.AUTH_USER_MODEL)),
                ('id_word', models.ForeignKey(db_column='id_word', on_delete=django.db.models.deletion.CASCADE, related_name='train_word', to='words.word')),
            ],
        ),
    ]
