# Generated by Django 4.2.4 on 2023-08-23 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_word_count', models.IntegerField(default=0)),
                ('train_seconds', models.IntegerField(default=0)),
                ('train_repeat', models.IntegerField(default=0)),
                ('train_tts_play', models.BooleanField(default=False)),
                ('exam_word_count', models.IntegerField(default=0)),
                ('exam_seconds', models.IntegerField(default=0)),
                ('exam_tts_play', models.BooleanField(default=False)),
                ('exam_difficulty', models.IntegerField(default=0)),
                ('user_find_hint', models.CharField(default='Korea', max_length=100)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='config_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
