# Generated by Django 4.2.4 on 2023-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="exam_difficulty",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="config",
            name="exam_seconds",
            field=models.IntegerField(default=10),
        ),
    ]
