# Generated by Django 4.2.4 on 2023-08-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(max_length=30)),
                ('en_phonetic', models.CharField(max_length=30)),
                ('word_class', models.CharField(max_length=30)),
                ('ko_phonetic', models.CharField(max_length=30)),
                ('ko_word_1', models.CharField(max_length=50)),
                ('ko_word_2', models.CharField(max_length=50)),
                ('ko_romanize', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
