# Generated by Django 4.2.4 on 2023-08-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
